# Generated by Django 4.1.5 on 2023-01-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_posts_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
